### ISSUE TITLE
Remove references to internal resources

### ISSUE THREAD

**Issue by gsherman** [DovetailSoftware/dovetail-bootstrap#17]
$dovetail-bootstrap\buildsupport\deploy.rb has a reference to 
http://focus.dovetailsoftware.com/nuget
which is inaccessible from the outside world. 
This causes rake to abort when a customer tries to build the project.

Need to fix this so that customers who try to build aren't blocked due to this.

**Comment by styson** [comment]
buildsupport/deploy.rb was removed long, long ago.

**Comment by KevM** [comment]
Yeah I think this is done. :8ball:

**Comment by styson** [comment]
Closing this since it is moot.
